# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubinformation',
            old_name='branch_sha',
            new_name='parent_branch_sha',
        ),
        migrations.AddField(
            model_name='githubinformation',
            name='tree_sha',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
