# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('repository_url', models.CharField(max_length=200)),
                ('repository_owner', models.CharField(max_length=200)),
                ('repository_base', models.CharField(max_length=200)),
                ('repository_head', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hook',
        ),
    ]
