# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDoApp', '0003_auto_20160523_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='githubinformation',
            name='user_email',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
