# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDoApp', '0005_githubinformation_branch_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubinformation',
            name='branch_sha',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default='none', size=None),
        ),
    ]
