# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDoApp', '0006_auto_20160523_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubinformation',
            name='branch_sha',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='none', max_length=200), size=None),
        ),
    ]
